FROM continuumio/miniconda3 AS conda
LABEL Description="iPyParaView base container."

SHELL ["/bin/bash", "-c"]

USER root

WORKDIR /root
COPY conda_requirements.txt .

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgl1-mesa-dev xvfb tini && \
    rm -rf /var/lib/apt/lists/*

RUN conda install --quiet --yes -c conda-forge --file conda_requirements.txt

COPY start_xvfb.sh /sbin/start_xvfb.sh
RUN chmod a+x /sbin/start_xvfb.sh

# Might not be needed:
# ARG LD_LIBRARY_PATH=/opt/conda/envs/ipy_pv_dev/lib
